### ISSUE TITLE
Improve Screen Architecture

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#113]
Currently we have code duplication and hard dependencies in every screen: Creating the corresponding screenView and appending / removing should be generalized to reduce duplication and dependencies and simplify testing (we just need to test it once, not for every screen again)

![Appendable Screens](https://www.lucidchart.com/publicSegments/view/4f7189a5-efb8-43bc-ac70-23d80a580d5b/image.png)

The new architecture would introduce the Mixin '''Appendable''' that deals with the appending and removing of the view. This can be tested once and applied to each screen.

**Comment by stravid** [comment]
Looks good.

If removing is more complicated (like the PlayScreen with all the bindings) the screen would override the remove method right?

**Comment by DominikGuzei** [comment]
exactly :-)

**Comment by tombu** [comment]
You are absolutely right @DominikGuzei! Again an improvement that we learned by writing tests and recognizing duplication ... :wink: 
I :heart: Mixins
