### ISSUE TITLE
$ or jQuery that's the question

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#12]
We use jQuery for DOM operations and for events. I prefer the short version, what do you think guys?

Either way, we should make the whole codebase consistent!

**Comment by bmedicke** [comment]
jQuery, more readable

**Comment by DominikGuzei** [comment]
:+1: for jQuery

**Comment by tombu** [comment]
jQuery :clap:

**Comment by roboshoes** [comment]
```
jQuery
```

:+1:
