### ISSUE TITLE
remove requirements in test files

### ISSUE THREAD

**Issue by tombu** [stravid/slotcars#120]
I recently recognized that we write way too much `#= require slotcars/...` statements in our test files. It should absolutely be enough to require the file which the test are for (and sometimes we need to require the classes that are used for initialization). Inside the tested file we list the requirements anyway.

**Comment by DominikGuzei** [comment]
I also thought about moving the complete requiring into the spec.js.coffee file. It would work and remove many lines of code that don't bring any value for the comprehension of the tests (in my opinion)

**Comment by stravid** [comment]
I agree.

But please explain following for me: I'm not sure why we don't do the same for the source code? Actually I can think of some  reasons, but please enlighten me :)

**Comment by tombu** [comment]
@DominikGuzei: Would also be a possibility. This would completely remove any `require` statements from all test files. The most important thing to me is that we care about the requirements in the production files. This way we can at least have an eye on the files´ dependencies. As you say: the `require` statements don´t add value to the tests ... but: I´m still in favour with my first advice.

Additional opinions?

**Comment by DominikGuzei** [comment]
For the source code we could do it, but I think that there the require statements actually add value (explicit dependencies ;-) and also bring classes to the front that have too many of them.

**Comment by stravid** [comment]
Thanks, I got it!

Let's remove them from the specs.
