### ISSUE TITLE
Unified Namespaces

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#128]
What top level namespaces do we need/want?

My current list:

`Shared`
`Build`
`Play`
`Home`
`Account`
`Tracks`
`Helpers`

What do you say?

**Comment by DominikGuzei** [comment]
sounds great, the only thing I am not quite content with (also at the moment) is the Helpers namespace.

I don't like that we have some very important classes (eg RaphaelPath) in helpers.math .. maybe they should go into shared? hmm..

**Comment by stravid** [comment]
I thought the same, I think shared could work well.
