### ISSUE TITLE
Highscores Implementation

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#156]
This started in pull request #154

We need a better (= faster) implementation for highscores, since it isn't an issue right now I wouldn't change it now. But I can't hurt if we discuss the different options we have right now.

@tombu suggested temporay tables / views with Postgresql, I suggested Redis.

What are the requirements for the highscores:
1. Track highscores: For every track we need a highscore. This means we want a sorted list of players ranked by their best run where every player entry has following attributes: `time`, `username` and `rank`. In addition it would be great to be able to only fetch a certain "window" from the highscores. This means things like "Top 10 Players", "5 Players around the current user", ...
2. User highscores: For every user we need a list of his highscores of each track he played. This means when user A played the tracks X, Y and Z we want to know his current rank and time on each of this tracks. Following attributes are needed for a user highscore entry: `time`, `rank` and `track_id` (maybe also `track_name` once we have those).
3. Change: Currently a nice to have, but in the future it would be great to know the number of ranks the user improved or how many ranks he lost since racing the track the last time.

Feel free to add and discuss requirements or suggest solutions.

**Comment by tombu** [comment]
Useful gems for sql views in rails: (just to remember them)
- https://github.com/activewarehouse/rails_sql_views
- https://github.com/lomba/schema_plus
