### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#157]
While building the notifications prototype I learned that notifications are hard. First of all we can have a huge number of different notifications:
- NewRunNotification - Every time someone finished a track and a new run is stored.
- NewRunOnCurrentTrackNotification - Every time someone finished the track you are currently playing.
- NewHighscoreNotification - Every time someone improves his time on a track.
- NewHighscoreOnCurrentTrackNotification - Every time someone improves his time on the track you are currently playing.
- UserBeatYourHighscoreNotification - Every time someone beats your time on a track.
- UserBeatYourHighscoreOnCurrentTrackNotification - Every time someone beats your time on the track you are currently playing.
- NewTrackNotification - Every time a new track gets published.

I think there a infinite different notifications but we can't display all of them.

**What are the interesting notifications?**

The second question is about displaying them. @DominikGuzei suggested an approach like Facebook uses, new notifications are never shown, instead a little red badge with a number indicates new notifications. This has the advantage that the user doesn't get distracted while racing. On the other hand there are players like Hannah who want the notifications to be shown immediately.

**How should notifications be implemented in the UI?**

**Comment by stravid** [comment]
Another big question:

**Should notifications be persistent?**
Persistent = When I go online, should I see all notifications which happened while I was offline?

**Comment by roboshoes** [comment]
Good question - my initial thought would be "No" but I can see upsides on both sides.
