### ISSUE TITLE
Consider to ember-layout

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#22]
With [ember-layout](https://github.com/ghempton/ember-layout) we get swappable view layouts which are way more awesome than manually appending / removing views of a 'content' area like the community application has!

:+1: i like it!

**Comment by roboshoes** [comment]
sure - looks convinient. :+1:

**Comment by DominikGuzei** [comment]
Is built in and used in form of dynamicView handlebars helpers
