### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#33]
In order to take part in the community
As a visitor
I want to register with my username

**Comment by stravid** [comment]
Interesting reads for more specific features like username: http://mihaia.com/post/77138388/clearance-login-with-username
https://github.com/thoughtbot/clearance/wiki/Authenticate-with-username

**Comment by DominikGuzei** [comment]
We have decided to create registration via Ajax instead of rendering separate pages with rails. This means that there is a new screen '''RegisterScreen''' introduced that holds the form and uses the new user model to register accounts.

**Comment by DominikGuzei** [comment]
Here is an overview of how the ajax registration could work in our application:

![Ajax Registration Flow](https://www.lucidchart.com/publicSegments/view/4f719de6-dd50-4744-8efc-1c790a580d5b/image.png)

**Comment by DominikGuzei** [comment]
Here are the mockups of possible validations:

![Validation Mockups](https://www.lucidchart.com/publicSegments/view/4f71a818-9f14-4b09-be2c-324f0a7b0e11/image.png)

**Comment by stravid** [comment]
After clicking 'Create Account' there should be a working/loading indicator of some kind so the user knows something is happening.

Why is there a password label but none for username and email? I would make this consistent.

Apart from this I think your two screenshots look good!

**Comment by roboshoes** [comment]
Nice. The only thing that might be of concern in the mock-ups is that we might want a confirm password field. I think that is pretty common in the average sign up process.

**Comment by DominikGuzei** [comment]
We decided against a password confirmation because typing on mobile devices it is the worst thing ever invented in the history of invented things.
