### ISSUE TITLE
Publish Track

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#35]
In order to publish my track
As a builder
I want to click the publish button and see my track in play mode

**Comment by stravid** [comment]
There are some things to discuss how the build screen should look and work. My proposal is this (explanation after the image): 

![Image](http://i.imgur.com/LHwKJ.png)

It's also saved on Lucidcharts if someone want's to modify it.

The build screen has four states:

**Draw**
After clicking on 'Build' in the home screen we go directly into this state. There is only the home button and a text telling you what to do (draw!).
**Edit**
After releasing the finger we switch to the edit state. Three additional buttons appear. Test, clear and Publish
**Test**
The test state has only one additional button to the home button, the stop testing button.
**Publish**
After clicking publish, there is a screen where you can enter a name / info (???) and you have a save button.

Your thoughts and ideas please!

**Comment by stravid** [comment]
Another idea to make the build screen more unique: Instead of the grass background we could use gravel.

**Comment by DominikGuzei** [comment]
Prinzipiell schauts sehr fein aus!

Hier ein paar Vorschläge:
- Den "Stop Testing" Button würde ich "Continue Editing" nennen (positive Formulierung + was passiert)
- Die Note bei Edit fände ich besser: "Now you can edit the track by moving the dots"
- Bei edit der "Test" Button wäre glaub ich klarer wenn er "Testdrive" heißt

**Comment by bmedicke** [comment]
I like Dave's idea of a progress representation a la amazon:
![amazon checkout](http://i.imgur.com/OEuOx.png)

Draw, Edit, Test, Publish, Play at the top of the screen. Lower left button jumps back one screen lower right loads the next screen in line.

**Comment by bmedicke** [comment]
![new design](http://i.imgur.com/JE17D.png)

**Comment by stravid** [comment]
I really like your version @bmedicke!

**Comment by tombu** [comment]
Looks good... but I don´t like it that I only can publish after I did the test drive. Shouldn´t it also be possible so publish directly after editing?

**Comment by bmedicke** [comment]
I think it motivates players to really try their track and not just assume it's fun to play because it looks fine.

**Comment by stravid** [comment]
If you really don't want to test drive you can just hit the publish button right away.

I think the advantage of having a linear flow beats the "you have to test drive" problem.

**Comment by DominikGuzei** [comment]
Yeah :+1: for benjis solution -> linear flow for president!
