### ISSUE TITLE
Ember.instanceOf instead of Ducktyping in the ScreenFactory

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#48]
Currently every screen has a property named like `isBuilderScreen` so we can test the ScreenFactory.
We should change this to a less ugly solution!

**Comment by tombu** [comment]
Ember already has the method 'detectInstance'. 
https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/tests/system/object/detectInstance_test.js
Maybe this is the way to go!?
