### ISSUE TITLE
Refactor Path Class

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#51]
Things to look into:
- When do we need to recalculate angles? What should be the default with `addPoint`?

**Comment by DominikGuzei** [comment]
- write comments to parts that are not self-speaking
- delete 'smooth' method since we don't need it anymore
- try to reduce private methods and maybe move advanced things like the clean algorithm into its own class

**Comment by tombu** [comment]
- don´t create it as `class` but let it and also LinkedList extend `Ember.Object` (consistency)
