### ISSUE TITLE
Animation between Views

### ISSUE THREAD

**Issue by roboshoes** [stravid/slotcars#56]
We need a standard way of animation Views in and out. I thought I will implement an `animateIn()` and `animateOut()`. Those functions get a callback which needs to be called when the animation is over. 

Technically, onle the `animateOut` needs the callabck.

I thought it should be implemented on the view, since this is logic that only belongs to the view.

Therefore:

`homeView.animateIn()`
`homeView.animateOut onAnimateOutComplete`

**Comment by stravid** [comment]
When the screen changes `CurrentScreen.destroy` is called which then removes all of its views.
Besides `remove` there is also `willDestroyElement` which is called right before the destruction.

For me it would make sense to hook up the animation functions somewhere there. **But** animations are timebased and asynchronous right? How does this work out with the current "screen managment" flow?

**Comment by roboshoes** [comment]
That would be the issue. It's not so much finding out when the view will be removed, It's more having the rest of the application wait until the animation is complete AND THEN actually removing the views. Logic wise completely different situations. Let's talk about it tomorrow.

**Comment by DominikGuzei** [comment]
we can use a state manager since state transitions can be asynchronous, thus supporting exactly what we need:
- onExit -> async animate out, when finished -> callback and transition is finished

**Comment by tombu** [comment]
see PR #195
