### ISSUE TITLE
Wrong crashing direction

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#75]
Currently the car rotation is updated one time too much before crashing. In hard curves this looks pretty weird because the car rotates into the new direction before it crashes which is not realistic at all. To be more realistic, the last direction before the "problematic" edge were the crash happened has to be used.

**Comment by tombu** [comment]
Yeah :smile:
We thought that we fixed this problem. The previous version rotated the car one step to far but the crash direction was the right one. I think I know where to fix it. This is issue is mine :wink:

**Comment by DominikGuzei** [comment]
nice :-) looking forward to the fix!
