### ISSUE TITLE
Move business logic of car - into car!

### ISSUE THREAD

**Issue by DominikGuzei** [stravid/slotcars#76]
Currently the game controller looks up positions on the track and tells the car model to set its position etc. This is business logic of the car that should be moved into the car. No other class than the car should know how to drive on a track and reset itself to the start position.

**Comment by tombu** [comment]
I absolutely disagree. The car should know how to do it but the game should tell what to do. This stuff which from your point of view is 'car logic' in my opinion is 'game logic'.
The only appropriate refactoring I see here here is to move lines 66-74 in a new method (e.g. driveTo)
See [game_controller.js.coffee](https://github.com/stravid/slotcars/blob/development/app/assets/javascripts/slotcars/play/controllers/game_controller.js.coffee)

**Comment by DominikGuzei** [comment]
let me explain: what happens when you add a second car?

in the current case you have to duplicate the whole logic for the second car etc. -> code smell

this logic is business logic of the car that works with the track model. the "game logic" is merely to tell the car that it should update and listening to events like crossed finish line.
